name: Release
on:
  push:
    branches:
      - main
jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create release
        run: |
          cd .vale/styles
          zip -r RedHat.zip RedHat
          gh release create v$GITHUB_RUN_NUMBER 'RedHat.zip'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
